# Generated by Django 2.0.8 on 2018-10-06 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Ongoing', 'Ongoing')], max_length=10)),
                ('emergency', models.CharField(choices=[('Fire', 'Fire')], max_length=10)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verifies', models.ManyToManyField(blank=True, related_name='is_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
