# Generated by Django 2.0.8 on 2018-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Fire', 'Fire')], default='Ongoing', max_length=10),
        ),
    ]
