# Generated by Django 2.0.8 on 2018-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Fire', 'Fire')], max_length=10),
        ),
    ]
