# Generated by Django 2.2.6 on 2019-10-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20191002_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=10),
        ),
    ]
