# Generated by Django 2.0.8 on 2018-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181006_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Fire', 'Fire')], max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Cleared', 'Cleared')], default='Ongoing', max_length=10),
        ),
    ]
