# Generated by Django 2.0.8 on 2018-10-06 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_auto_20181006_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='responder',
            field=models.ManyToManyField(blank=True, related_name='is_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=10),
        ),
    ]
