# Generated by Django 2.0.8 on 2018-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181006_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Cleared', 'Cleared')], default='Ongoing', max_length=10),
        ),
    ]
