# Generated by Django 2.0.8 on 2018-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_notification_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Crime', 'Crime')], max_length=10),
        ),
    ]
