# Generated by Django 2.0.8 on 2018-09-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180920_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Fire', 'Fire')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
