# Generated by Django 2.0.8 on 2018-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20181009_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
