# Generated by Django 2.0.8 on 2018-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=10),
        ),
    ]
