# Generated by Django 2.0.8 on 2018-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20180920_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='emergency',
            field=models.CharField(choices=[('Fire', 'Fire')], max_length=10),
        ),
    ]
