# Generated by Django 2.0.8 on 2018-10-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=30)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Responder')),
            ],
        ),
    ]
