# Generated by Django 2.0.8 on 2018-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180918_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='station',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Fire', 'Fire')], max_length=10),
        ),
    ]
