# Generated by Django 2.0.8 on 2018-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180918_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='station',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Crime', 'Crime')], max_length=10),
        ),
    ]
