# Generated by Django 2.0.8 on 2018-09-20 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180920_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='responder',
            name='station',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Fire', 'Fire')], max_length=10),
        ),
    ]
