# Generated by Django 2.0.8 on 2018-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180920_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='station',
            field=models.CharField(choices=[('Fire', 'Fire Station')], max_length=10),
        ),
    ]
